export type OpeningLine = readonly [
  moves: string,
  name: string,
  eco: string,
  origin: string,
  plan: string,
];
export interface OpeningInfo {
  name: string;
  eco: string;
  origin: string;
  plan: string;
  depth: number;
}

export const BOOK_LINES: readonly OpeningLine[] = [
  // ---- Open games: 1.e4 e5
  [
    "e4 e5",
    "Open Game",
    "C20",
    "The oldest recorded battleground: both sides stake a claim in the centre at once. Lucena's 1497 treatise and Greco's 17th-century games are almost all open games.",
    "Fast development, early castling, and the fight for d4 and d5. Tactics come quickly because both king's bishops see the f-pawns.",
  ],
  [
    "e4 e5 Nf3 Nc6 Bb5",
    "Ruy Lopez (Spanish)",
    "C60",
    "Analysed in the Göttingen manuscript (c.1490) and named for Ruy López de Segura, the Spanish priest whose 1561 book gave it a systematic treatment. The main line of top-level chess for over a century.",
    "White pressures e5 indirectly by threatening the c6 knight, then builds slowly with c3, d4 and the Nb1-d2-f1-g3 regrouping. Black holds the centre and waits for a chance to counter with ...d5 or a queenside expansion.",
  ],
  [
    "e4 e5 Nf3 Nc6 Bb5 a6",
    "Morphy Defence",
    "C70",
    "Paul Morphy's 1850s idea: ask the bishop a question at once. Retreating to a4 keeps the tension; taking on c6 gives Black the bishop pair.",
    "...a6 and ...b5 gain queenside space and can later hunt the bishop with ...Na5. White accepts the tempo loss for a lasting bind on e5.",
  ],
  [
    "e4 e5 Nf3 Nc6 Bb5 a6 Ba4 Nf6 O-O Be7 Re1 b5 Bb3 d6 c3 O-O h3",
    "Closed Ruy Lopez",
    "C84",
    "The classical position reached in thousands of master games since the 1890s. Chigorin, Capablanca and Karpov all built careers on it.",
    "White plays d4 and manoeuvres the knight to g3 or f1; Black chooses a plan for the c6 knight (Chigorin, Breyer, Zaitsev). A slow, strategic middlegame where one tempo decides.",
  ],
  [
    "e4 e5 Nf3 Nc6 Bb5 a6 Ba4 Nf6 O-O Be7 Re1 b5 Bb3 d6 c3 O-O h3 Na5 Bc2 c5 d4 Qc7",
    "Chigorin Variation",
    "C96",
    "Mikhail Chigorin's late-19th-century plan, the mainstay of the Closed Spanish for decades.",
    "Black grabs queenside space with ...c5 and ...Qc7, keeping e5 solid. White decides whether to close the centre with d5 or keep tension with Nbd2.",
  ],
  [
    "e4 e5 Nf3 Nc6 Bb5 a6 Ba4 Nf6 O-O Be7 Re1 b5 Bb3 d6 c3 O-O h3 Nb8",
    "Breyer Variation",
    "C95",
    "Gyula Breyer proposed it around 1911; Spassky and later Karpov made it respectable in the 1960s and 70s.",
    "The knight retreats to reroute via d7, freeing the c-pawn and supporting e5. Ugly-looking, deeply logical.",
  ],
  [
    "e4 e5 Nf3 Nc6 Bb5 a6 Ba4 Nf6 O-O Be7 Re1 b5 Bb3 d6 c3 O-O h3 Bb7",
    "Zaitsev Variation",
    "C92",
    "Igor Zaitsev, Karpov's second, developed it in the 1980s; it became the battleground of the Karpov–Kasparov matches.",
    "Black activates the bishop and plays ...Re8, ...Bf8 to pressure e4. Extremely concrete: both sides need precise preparation.",
  ],
  [
    "e4 e5 Nf3 Nc6 Bb5 a6 Ba4 Nf6 O-O Be7 Re1 b5 Bb3 O-O c3 d5",
    "Marshall Attack",
    "C89",
    "Frank Marshall unveiled it against Capablanca in New York, 1918, reportedly after years of secret preparation. Capablanca won anyway, but the gambit has been a headache for White ever since.",
    "Black sacrifices a pawn for a kingside attack with ...Bd6, ...Qh4 and ...Nf6-g4 ideas. White must know the antidotes or avoid it with an anti-Marshall like 8.a4 or 8.h3.",
  ],
  [
    "e4 e5 Nf3 Nc6 Bb5 a6 Ba4 Nf6 O-O Nxe4",
    "Open Ruy Lopez",
    "C80",
    "Tarrasch's preference, later a weapon of Korchnoi and Yusupov: grab the pawn and fight.",
    "After d4 b5 Bb3 d5 dxe5 Be6 Black has active pieces and a central pawn; White has the e5 wedge and attacking chances. Tactical, unbalanced.",
  ],
  [
    "e4 e5 Nf3 Nc6 Bb5 a6 Ba4 Nf6 O-O Nxe4 d4 b5 Bb3 d5 dxe5 Be6",
    "Open Ruy Lopez, main line",
    "C80",
    "Standard position of the Open Spanish since the Steinitz era.",
    "White targets the e4 knight and the d5 pawn; Black seeks ...Bc5 and ...O-O with active play.",
  ],
  [
    "e4 e5 Nf3 Nc6 Bb5 a6 Bxc6",
    "Exchange Variation",
    "C68",
    "Emanuel Lasker used it to win at St Petersburg 1914; Fischer revived it at the 1966 Havana Olympiad with three wins in a row.",
    "White gives up the bishop pair for a healthier pawn structure: after d4 and trades, White's 4-v-3 kingside majority is a real endgame asset. Black relies on the two bishops.",
  ],
  [
    "e4 e5 Nf3 Nc6 Bb5 Nf6",
    "Berlin Defence",
    "C65",
    "Analysed by the Berlin school in the 1840s, dismissed as drawish, then resurrected by Kramnik to neutralise Kasparov in their 2000 world championship match.",
    "Black develops before deciding on ...a6. The main line leads to a queenless middlegame (the Berlin Wall) where Black's bishop pair offsets a damaged pawn structure.",
  ],
  [
    "e4 e5 Nf3 Nc6 Bb5 Nf6 O-O Nxe4 d4 Nd6 Bxc6 dxc6 dxe5 Nf5 Qxd8+ Kxd8",
    "Berlin Wall",
    "C67",
    "The endgame Kramnik used to blunt Kasparov's 1.e4 in 2000.",
    "White has the kingside majority and a lead in development; Black has the bishop pair and a solid, long-term structure. Endgame technique decides.",
  ],
  [
    "e4 e5 Nf3 Nc6 Bb5 f5",
    "Schliemann Defence",
    "C63",
    "Carl Jaenisch analysed it in the 1840s; Adolf Schliemann popularised it. A gambit in the sharpest tradition.",
    "Black attacks the e4 pawn immediately and aims for open lines. White's most testing reply is Nc3.",
  ],
  [
    "e4 e5 Nf3 Nc6 Bb5 d6",
    "Steinitz Defence",
    "C62",
    "Wilhelm Steinitz's solid choice: defend e5 with the pawn and accept a cramped but sound position.",
    "Black keeps a tight centre; White gains space with d4. The Modern Steinitz (with ...a6 first) is the improved version.",
  ],
  [
    "e4 e5 Nf3 Nc6 Bb5 a6 Ba4 d6",
    "Modern Steinitz Defence",
    "C71",
    "Steinitz's setup improved by inserting ...a6, favoured by Keres and Alekhine.",
    "Black is solid on e5 and may later play ...f5. White presses with c3 and d4.",
  ],
  [
    "e4 e5 Nf3 Nc6 Bb5 a6 Ba4 Nf6 O-O b5 Bb3 Bb7",
    "Arkhangelsk Variation",
    "C78",
    "Developed by players from Arkhangelsk in the 1970s and 80s.",
    "Black puts the bishop on the long diagonal to pressure e4 and often follows with ...Bc5. Sharp and active.",
  ],
  // ---- Italian complex
  [
    "e4 e5 Nf3 Nc6 Bc4",
    "Italian Game",
    "C50",
    "The workhorse of Renaissance chess: Polerio, Greco and the Italian masters analysed it in the 16th and 17th centuries, and it opens most of the earliest surviving games.",
    "The bishop eyes f7, the weakest point in Black's camp. White can go for quick tactics (Evans, Two Knights) or a slow build with c3 and d3.",
  ],
  [
    "e4 e5 Nf3 Nc6 Bc4 Bc5",
    "Giuoco Piano",
    "C53",
    '"The quiet game", though its main lines are anything but. Greco\'s manuscripts (c.1620) are full of it.',
    "Symmetrical bishops, symmetrical aims. White chooses between the central push c3 and d4 or the modern slow treatment with d3.",
  ],
  [
    "e4 e5 Nf3 Nc6 Bc4 Bc5 c3 Nf6 d4 exd4 cxd4 Bb4+",
    "Giuoco Piano, main line",
    "C54",
    "The classical pawn centre with a pin: Greco's line, still played.",
    "White has a big centre and open lines; Black hits it with ...Nxe4 or ...d5. Greco Attack (Nc3) versus Bd2 keeps this alive.",
  ],
  [
    "e4 e5 Nf3 Nc6 Bc4 Bc5 d3",
    "Giuoco Pianissimo",
    "C50",
    'The "very quiet game". Elite players rediscovered it in the 2010s (Carlsen, Caruana, Anand) as a way to get Spanish-style play without Spanish theory.',
    "White delays d4, plays c3, Nbd2, Re1 and often h3 and Bb3, keeping a small, durable edge. Manoeuvring chess.",
  ],
  [
    "e4 e5 Nf3 Nc6 Bc4 Bc5 b4",
    "Evans Gambit",
    "C51",
    "Captain William Davies Evans, a Welsh sea captain, introduced it around 1827. Morphy and Anderssen adored it; Kasparov beat Anand with it in 1995.",
    "White gives a pawn to gain tempi with c3 and d4, building a huge centre and open lines for an attack on f7. Black must return material or defend precisely.",
  ],
  [
    "e4 e5 Nf3 Nc6 Bc4 Bc5 b4 Bxb4 c3 Ba5 d4",
    "Evans Gambit Accepted",
    "C52",
    "The classical acceptance, Anderssen's battleground.",
    "White's pawns roll forward; Black's bishop on a5 pins the c3 pawn. Lasker's defence (...d6 and returning the pawn) is the sober answer.",
  ],
  [
    "e4 e5 Nf3 Nc6 Bc4 Nf6",
    "Two Knights Defence",
    "C55",
    "Polerio analysed it around 1600. Black counterattacks e4 instead of copying White.",
    "White's Ng5 attacks f7 immediately; the calmer d3 leads to Italian-style play. Black must know the tactics of 4.Ng5.",
  ],
  [
    "e4 e5 Nf3 Nc6 Bc4 Nf6 Ng5 d5 exd5 Na5",
    "Two Knights, main line",
    "C58",
    "The principled answer to 4.Ng5, worked out in the 19th century.",
    "Black sacrifices a pawn for a lead in development after Bb5+ c6 dxc6 bxc6. Active play compensates.",
  ],
  [
    "e4 e5 Nf3 Nc6 Bc4 Nf6 Ng5 d5 exd5 Nxd5 Nxf7",
    "Fried Liver Attack",
    "C57",
    'Polerio\'s "Fegatello" (c.1600): a knight sacrifice that drags the king into the open. A staple of club chess for four centuries.',
    "After ...Kxf7 Qf3+ Ke6 White attacks the exposed king with d4 and Nc3. Black is objectively fine but must defend accurately.",
  ],
  [
    "e4 e5 Nf3 Nc6 Bc4 Nf6 d4",
    "Two Knights, Scotch Gambit style",
    "C56",
    "Max Lange and 19th-century attacking players preferred opening the centre.",
    "White sacrifices a pawn for rapid development and open lines against the king.",
  ],
  [
    "e4 e5 Nf3 Nc6 Bc4 Be7",
    "Hungarian Defence",
    "C50",
    "Named after a Pest–Paris correspondence game of 1842.",
    "Black avoids all the Italian tactics with a modest bishop. Solid, slightly passive.",
  ],
  // ---- Scotch
  [
    "e4 e5 Nf3 Nc6 d4",
    "Scotch Game",
    "C44",
    "Named for the Edinburgh vs London correspondence match of 1824. Out of fashion for a century until Kasparov used it against Karpov in 1990.",
    "White opens the centre immediately. Black gets easy development; White gets space and a lead in the fight for d5.",
  ],
  [
    "e4 e5 Nf3 Nc6 d4 exd4 Nxd4 Bc5",
    "Scotch, Classical Variation",
    "C45",
    "The old main line: pressure the knight and provoke Be3.",
    "Black develops actively; White may play Nxc6 or Be3 followed by c3 and Nc2 to keep the centre.",
  ],
  [
    "e4 e5 Nf3 Nc6 d4 exd4 Nxd4 Nf6",
    "Scotch, Schmidt Variation",
    "C45",
    "Ernst Schmidt's counterattack on e4.",
    "Leads to the Mieses line after Nxc6 bxc6 e5, where Black's doubled pawns are offset by active pieces.",
  ],
  [
    "e4 e5 Nf3 Nc6 d4 exd4 Nxd4 Nf6 Nxc6 bxc6 e5 Qe7 Qe2 Nd5 c4",
    "Mieses Variation",
    "C45",
    "Jacques Mieses's line, revived by Kasparov and Timman in the 1990s.",
    "White pushes the knight back with c4; Black has ...Ba6 and pressure on the e-file. Unbalanced and rich.",
  ],
  [
    "e4 e5 Nf3 Nc6 d4 exd4 Bc4",
    "Scotch Gambit",
    "C44",
    "A 19th-century favourite; Morphy played it.",
    "White delays recapturing to develop with tempo. Transposes to Italian lines or leads to sharp play after ...Bc5 c3.",
  ],
  [
    "e4 e5 Nf3 Nc6 d4 exd4 c3",
    "Göring Gambit",
    "C44",
    "Carl Göring played it in the 1870s. A close relative of the Danish Gambit.",
    "White offers one or two pawns for open lines and rapid development. Declining with ...d5 is the modern recommendation.",
  ],
  // ---- Petrov, Philidor
  [
    "e4 e5 Nf3 Nf6",
    "Petrov Defence",
    "C42",
    "Alexander Petrov and Carl Jaenisch analysed it in the 1840s (the Russian Game). Its reputation as a drawing weapon was cemented by Kramnik and Caruana.",
    "Black counterattacks e4 rather than defending e5. Symmetrical structures, early simplifications, and a solid road to equality.",
  ],
  [
    "e4 e5 Nf3 Nf6 Nxe5 d6 Nf3 Nxe4 d4 d5 Bd3",
    "Petrov, Classical main line",
    "C42",
    "The standard position since the 19th century.",
    "White challenges the e4 knight with c4 or Re1; Black develops with ...Nc6, ...Be7 and holds the centre.",
  ],
  [
    "e4 e5 Nf3 d6",
    "Philidor Defence",
    "C41",
    "François-André Danican Philidor, the 18th-century master who declared pawns the soul of chess, recommended it in 1749.",
    "Black supports e5 with a pawn, keeps a compact centre and often fianchettoes nothing: a modest, resilient setup. White has more space.",
  ],
  // ---- Sicilian
  [
    "e4 c5",
    "Sicilian Defence",
    "B20",
    "Polerio noted it in 1594; the name was fixed by Jacob Sarratt in 1813. Louis Paulsen made it respectable in the 1870s, and since the 1950s it has been Black's most popular reply to 1.e4.",
    "Black fights for d4 with a flank pawn, keeping the position asymmetrical. White usually opens the centre with d4 to gain development; Black plays for the long term on the queenside.",
  ],
  [
    "e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 a6",
    "Najdorf Variation",
    "B90",
    "Miguel Najdorf's flexible waiting move became the weapon of Fischer and Kasparov, who both used it as the backbone of their repertoires.",
    "...a6 stops Nb5 and prepares ...e5 or ...b5. White chooses an attacking setup (Bg5, Be3 with f3, Bc4) and Black counters on the queenside.",
  ],
  [
    "e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 a6 Bg5 e6 f4",
    "Najdorf, main line 6.Bg5",
    "B96",
    "The critical test of the Najdorf in the Fischer era, home of the Poisoned Pawn (...Qb6).",
    "White throws the f-pawn forward; Black chooses ...Be7, ...Qb6 or ...Nbd7. Extremely sharp.",
  ],
  [
    "e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 a6 Be3 e5 Nb3",
    "Najdorf, English Attack",
    "B90",
    "Named for the English grandmasters (Nunn, Short, Chandler) who developed it in the 1980s.",
    "White plays f3, Qd2, O-O-O and g4; Black castles short and races with ...b5. Opposite-side attacks.",
  ],
  [
    "e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 a6 Be2",
    "Najdorf, Classical 6.Be2",
    "B92",
    "Karpov's choice: a quiet move against a sharp defence.",
    "White castles and plays a4 or f4 later; Black replies ...e5. Positional battle around d5.",
  ],
  [
    "e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 a6 Bc4",
    "Najdorf, Fischer–Sozin Attack",
    "B86",
    "Veniamin Sozin's idea, adopted by Fischer as his main weapon against the Najdorf.",
    "The bishop on b3 targets f7 and e6. Black plays ...e6, ...b5 and ...Bb7.",
  ],
  [
    "e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 g6",
    "Dragon Variation",
    "B70",
    "Fyodor Dus-Chotimirsky named it in 1901 after the constellation Draco, which he thought the pawn structure resembled.",
    "Black's bishop on g7 rakes the long diagonal towards b2. White's most dangerous plan is the Yugoslav Attack; Black counters on the c-file.",
  ],
  [
    "e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 g6 Be3 Bg7 f3 O-O Qd2 Nc6 O-O-O",
    "Yugoslav Attack",
    "B76",
    'Developed by Yugoslav masters in the 1950s, building on Rauzer\'s earlier ideas. Fischer called the plan "pry open the h-file, sac, sac, mate".',
    "White castles long and storms with h4-h5; Black uses ...Rc8, ...Ne5-c4 and exchange sacrifices on c3. Both kings are targets.",
  ],
  [
    "e4 c5 Nf3 Nc6 d4 cxd4 Nxd4 g6",
    "Accelerated Dragon",
    "B34",
    "Black fianchettoes without ...d6, hoping for ...d5 in one go.",
    "Avoids the Yugoslav Attack but allows the Maroczy Bind with c4. Flexible, positional Dragon.",
  ],
  [
    "e4 c5 Nf3 Nc6 d4 cxd4 Nxd4 g6 c4",
    "Maroczy Bind",
    "B36",
    "Géza Maróczy's clamp on d5, feared for a century.",
    "White's pawns on c4 and e4 deny Black the ...d5 break. Black plays for ...b5 or slow piece pressure.",
  ],
  [
    "e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 e6",
    "Scheveningen Variation",
    "B80",
    "Named after the 1923 tournament in the Dutch seaside town. Kasparov's most reliable Sicilian.",
    "Black's small centre (d6, e6) is elastic and solid. White's sharpest try is the Keres Attack (g4); Black counters with ...b5 and ...Bb7.",
  ],
  [
    "e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 e6 g4",
    "Keres Attack",
    "B81",
    "Paul Keres's pawn thrust, the reason many players reach the Scheveningen via the Najdorf move order.",
    "White gains space and drives the f6 knight away; Black must react precisely with ...h6 or ...e5.",
  ],
  [
    "e4 c5 Nf3 Nc6 d4 cxd4 Nxd4 Nf6 Nc3 e5",
    "Sveshnikov Variation",
    "B33",
    "Evgeny Sveshnikov and Gennady Timoshchenko developed it in the 1970s against orthodox opinion. Carlsen used it in his 2018 title match.",
    "Black accepts a backward d6 pawn and a hole on d5 for active pieces and the ...f5 break. Dynamic, deeply analysed.",
  ],
  [
    "e4 c5 Nf3 Nc6 d4 cxd4 Nxd4 Nf6 Nc3 e5 Ndb5 d6 Bg5 a6 Na3 b5",
    "Sveshnikov, main line",
    "B33",
    "The critical tabiya since the 1980s.",
    "White plays Bxf6 and Nd5; Black uses the bishop pair and ...f5. Sharp, concrete play.",
  ],
  [
    "e4 c5 Nf3 Nc6 d4 cxd4 Nxd4 e5",
    "Kalashnikov Variation",
    "B32",
    "A 1980s cousin of the Sveshnikov, named after the rifle for its directness.",
    "Same hole on d5, but with the knight still on g8 Black keeps more options.",
  ],
  [
    "e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 Nc6",
    "Classical Sicilian",
    "B56",
    "The oldest Open Sicilian setup: develop and see.",
    "White's Richter–Rauzer (Bg5) is the main test; Black keeps a flexible structure.",
  ],
  [
    "e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 Nc6 Bg5",
    "Richter–Rauzer Attack",
    "B60",
    "Kurt Richter and Vsevolod Rauzer, 1930s: the pin that shapes the Classical Sicilian.",
    "White plans Qd2 and O-O-O; Black chooses ...e6 and ...Bd7 or ...Qb6.",
  ],
  [
    "e4 c5 Nf3 e6 d4 cxd4 Nxd4 Nc6",
    "Taimanov Variation",
    "B44",
    "Mark Taimanov's flexible system, a favourite of positional players.",
    "Black keeps the d-pawn back and develops with ...Qc7 and ...a6. White chooses between Nb5, Nc3 and the Maroczy setup.",
  ],
  [
    "e4 c5 Nf3 e6 d4 cxd4 Nxd4 a6",
    "Kan Variation",
    "B41",
    "Ilya Kan's system: maximum flexibility, minimum commitment.",
    "Black may play ...Qc7, ...Nf6, ...d6 or ...b5 depending on White's setup. White often plays Bd3 or c4.",
  ],
  [
    "e4 c5 Nf3 e6 d4 cxd4 Nxd4 Nf6 Nc3 Nc6",
    "Four Knights Sicilian",
    "B45",
    "A route to the Sveshnikov or Scheveningen with fewer forcing lines.",
    "Black's ...Bb4 pin and ...e5 are the main ideas.",
  ],
  [
    "e4 c5 Nc3 Nc6 g3",
    "Closed Sicilian",
    "B25",
    "Spassky's weapon and Smyslov's, avoiding the theory of the Open Sicilian.",
    "White fianchettoes and plays f4, Nf3 and a slow kingside build. Black expands on the queenside with ...Rb8 and ...b5.",
  ],
  [
    "e4 c5 Nc3 Nc6 f4",
    "Grand Prix Attack",
    "B23",
    "Named after the British weekend Grand Prix circuit of the 1980s, where Hebden and Hodgson used it to great effect.",
    "White aims for Bb5 or Bc4, O-O and a direct kingside attack with f5. Black counters with ...g6 and ...d5 ideas.",
  ],
  [
    "e4 c5 c3",
    "Alapin Variation",
    "B22",
    "Semyon Alapin's 19th-century idea, revived in the 1980s by Sveshnikov of all people.",
    "White prepares d4 without allowing ...cxd4 Nxd4. Black's best replies are ...Nf6 (hitting e4) and ...d5.",
  ],
  [
    "e4 c5 c3 Nf6 e5 Nd5",
    "Alapin, 2...Nf6",
    "B22",
    "The most popular reply: provoke e5 and target the pawn.",
    "White gets space; Black gets a good knight on d5 and pressure on the e5 pawn.",
  ],
  [
    "e4 c5 c3 d5 exd5 Qxd5",
    "Alapin, 2...d5",
    "B22",
    "The direct challenge: an open centre with the queen out early.",
    "White gains tempi on the queen with Nf3 and d4; Black has easy development and an isolated d-pawn to attack.",
  ],
  [
    "e4 c5 d4 cxd4 c3",
    "Smith–Morra Gambit",
    "B21",
    "Pierre Morra analysed it in the 1950s; Ken Smith championed it in America.",
    "White gives a pawn for open c- and d-files and rapid development. Declining with ...Nf6 or ...d3 is safe.",
  ],
  [
    "e4 c5 Nf3 d6 Bb5+",
    "Moscow Variation",
    "B51",
    "A modern anti-Sicilian, favoured by positional players who want a quiet game.",
    "White trades bishops or gains a tempo on the c6 knight; Black chooses ...Bd7, ...Nd7 or ...Nc6.",
  ],
  [
    "e4 c5 Nf3 Nc6 Bb5",
    "Rossolimo Variation",
    "B30",
    "Nicolas Rossolimo's line, a favourite of Fischer and later Carlsen.",
    "White threatens Bxc6 to damage the pawns, then plays a Spanish-style game. Black replies ...g6, ...e6 or ...d6.",
  ],
  // ---- French
  [
    "e4 e6",
    "French Defence",
    "C00",
    "Named for a Paris vs London correspondence match of 1834. Nimzowitsch and Botvinnik gave it its strategic depth; Korchnoi its fighting reputation.",
    "Black builds a solid pawn chain with ...d5 and counterattacks the base of White's chain (d4) with ...c5. The bad light-squared bishop is the eternal French problem.",
  ],
  [
    "e4 e6 d4 d5 e5",
    "Advance Variation",
    "C02",
    "Nimzowitsch loved it; Sveshnikov and later Grischuk modernised it.",
    "White gains space and clamps down on the kingside; Black hammers d4 with ...c5, ...Nc6 and ...Qb6.",
  ],
  [
    "e4 e6 d4 d5 e5 c5 c3 Nc6 Nf3 Qb6",
    "Advance, main line",
    "C02",
    "The classical tabiya of the Advance French.",
    "Black piles on d4 and b2; White defends with Be2 or a3 and later plays Bd3 with a kingside attack.",
  ],
  [
    "e4 e6 d4 d5 exd5",
    "Exchange Variation",
    "C01",
    "The quiet option, chosen by those who want to avoid the pawn chain fight.",
    "A symmetrical structure; play is about piece activity and the e-file.",
  ],
  [
    "e4 e6 d4 d5 Nd2",
    "Tarrasch Variation",
    "C03",
    "Siegbert Tarrasch's idea to avoid the ...Bb4 pin. Karpov's main weapon against the French.",
    "The knight stays flexible and c3 is available. Black chooses between ...c5 (open) and ...Nf6 (closed).",
  ],
  [
    "e4 e6 d4 d5 Nd2 c5",
    "Tarrasch, 3...c5",
    "C07",
    "The freeing break, often leading to an isolated queen's pawn for Black.",
    "Black gets active pieces for a structural weakness; White plays against the d5 pawn.",
  ],
  [
    "e4 e6 d4 d5 Nd2 Nf6",
    "Tarrasch, 3...Nf6",
    "C05",
    "The closed treatment: White plays e5 and a chain fight follows.",
    "Black attacks d4 with ...c5 and ...Nc6; White defends with c3 and Ne2, eyeing the kingside.",
  ],
  [
    "e4 e6 d4 d5 Nc3 Bb4",
    "Winawer Variation",
    "C15",
    "Szymon Winawer played it in the 1870s; Botvinnik made it a world championship weapon.",
    "Black pins and usually trades on c3, saddling White with doubled pawns. White gets the bishop pair and a kingside attack. Deeply unbalanced.",
  ],
  [
    "e4 e6 d4 d5 Nc3 Bb4 e5 c5 a3 Bxc3+ bxc3 Ne7",
    "Winawer, main line",
    "C18",
    "The classical battleground of the Winawer.",
    "White plays Qg4 against the kingside; Black plays ...Qc7 or ...Qa5 and attacks c3 and the queenside.",
  ],
  [
    "e4 e6 d4 d5 Nc3 Nf6",
    "Classical French",
    "C11",
    "The oldest French main line, played before Winawer's pin was fashionable.",
    "White's e5 (Steinitz) gains space; Bg5 allows the Burn or MacCutcheon. A chain fight with kingside pressure for White.",
  ],
  [
    "e4 e6 d4 d5 Nc3 Nf6 e5 Nfd7",
    "Steinitz Variation",
    "C11",
    "Steinitz's plan of grabbing space at once.",
    "White plays f4, Nf3 and Be3; Black attacks d4 with ...c5 and ...Nc6, often sacrificing on d4.",
  ],
  [
    "e4 e6 d4 d5 Nc3 Nf6 Bg5 dxe4",
    "Burn Variation",
    "C11",
    "Amos Burn's simplifying answer to the pin.",
    "Black relieves the tension and develops the bad bishop later; White keeps a small space edge.",
  ],
  [
    "e4 e6 d4 d5 Nc3 Nf6 Bg5 Bb4",
    "MacCutcheon Variation",
    "C12",
    "John Lindsay McCutcheon beat Steinitz with it in 1885.",
    "Black counter-pins and lets White wreck the kingside pawns for activity. Sharp and double-edged.",
  ],
  [
    "e4 e6 d4 d5 Nc3 dxe4",
    "Rubinstein Variation",
    "C10",
    "Akiba Rubinstein's solid choice, adopted by Fischer.",
    "Black gives up the centre for easy development and a sound structure. White has space; the fight is over who uses it.",
  ],
  // ---- Caro-Kann
  [
    "e4 c6",
    "Caro–Kann Defence",
    "B10",
    "Horatio Caro and Marcus Kann published analysis in 1886. Capablanca, Botvinnik, Petrosian and Karpov all used it.",
    "Black prepares ...d5 without blocking the c8 bishop. Solid structure, few weaknesses; the cost is a slower development.",
  ],
  [
    "e4 c6 d4 d5 e5 Bf5",
    "Advance Variation",
    "B12",
    "Tal used it; Nigel Short's 4.Nf3 e6 5.Be2 treatment made it the main line in the 1990s.",
    "White grabs space; Black develops the bishop outside the chain and hits d4 with ...c5. A pawn-chain battle.",
  ],
  [
    "e4 c6 d4 d5 Nc3 dxe4 Nxe4 Bf5",
    "Classical Variation",
    "B18",
    "The traditional main line, a Capablanca and Karpov favourite.",
    "Black develops the bishop before ...e6; White gains kingside space with Ng3 and h4-h5.",
  ],
  [
    "e4 c6 d4 d5 Nc3 dxe4 Nxe4 Bf5 Ng3 Bg6 h4 h6 Nf3 Nd7",
    "Classical, main line",
    "B19",
    "The tabiya of countless world championship games.",
    "White plays h5 and Bd3 to trade bishops; Black castles long or short and relies on a rock-solid structure.",
  ],
  [
    "e4 c6 d4 d5 Nc3 dxe4 Nxe4 Nd7",
    "Karpov Variation",
    "B17",
    "Karpov's favourite: prepare ...Ngf6 without allowing doubled pawns.",
    "Black keeps the structure intact; White has a lead in development and attacking tries with Bc4 or Ng5.",
  ],
  [
    "e4 c6 d4 d5 Nc3 dxe4 Nxe4 Nf6 Nxf6+ gxf6",
    "Bronstein–Larsen Variation",
    "B16",
    "Bronstein and Larsen accepted doubled f-pawns for open lines and the bishop pair.",
    "Black plays ...Bf5, ...Qc7 and castles long; the half-open g-file is an attacking asset.",
  ],
  [
    "e4 c6 d4 d5 exd5 cxd5",
    "Exchange Variation",
    "B13",
    "A quiet line, sometimes leading to the Panov.",
    "Symmetrical pawns; White tries Bd3 and a minority attack or c4 for the Panov structure.",
  ],
  [
    "e4 c6 d4 d5 exd5 cxd5 c4",
    "Panov–Botvinnik Attack",
    "B14",
    "Vasily Panov's 1930 idea, refined by Botvinnik.",
    "White accepts an isolated d-pawn for active pieces and space. Black blockades on d5 and aims for the endgame.",
  ],
  [
    "e4 c6 Nc3 d5 Nf3",
    "Two Knights Variation",
    "B11",
    "Fischer's early preference.",
    "White develops quickly and delays d4; Black's ...Bg4 pin is the main reply.",
  ],
  [
    "e4 c6 d4 d5 f3",
    "Fantasy Variation",
    "B12",
    "An offbeat line that supports e4 with the f-pawn.",
    "White keeps a big centre; Black challenges it with ...e6 and ...c5 or ...dxe4 fxe4 e5.",
  ],
  // ---- Scandinavian, Pirc, Modern, Alekhine
  [
    "e4 d5",
    "Scandinavian Defence",
    "B01",
    "The oldest recorded chess game (Valencia, 1475) opened this way. Scandinavian masters analysed it in the 19th century; Anand used it against Kasparov in 1995.",
    "Black challenges e4 at once and recaptures with the queen. White gains tempi on the queen; Black gets a solid Caro-Kann-like structure.",
  ],
  [
    "e4 d5 exd5 Qxd5 Nc3 Qa5",
    "Scandinavian, 3...Qa5",
    "B01",
    "The classical retreat, keeping the queen active.",
    "Black plays ...c6, ...Bf5 and ...e6; White uses the tempi for d4, Nf3 and Bc4.",
  ],
  [
    "e4 d5 exd5 Qxd5 Nc3 Qd6",
    "Scandinavian, 3...Qd6",
    "B01",
    "A modern retreat popularised by Sergei Tiviakov.",
    "The queen supports ...c6 and ...e5 ideas from a safer square.",
  ],
  [
    "e4 d5 exd5 Nf6",
    "Scandinavian, Modern Variation",
    "B01",
    "Marshall's gambit-style treatment.",
    "Black recaptures with the knight, keeping the queen home. White may hold the pawn with c4 or return it with d4.",
  ],
  [
    "e4 d6 d4 Nf6 Nc3 g6",
    "Pirc Defence",
    "B07",
    "Vasja Pirc and Anatoly Ufimtsev developed it in the 1930s and 40s: a hypermodern approach against 1.e4.",
    "Black lets White build a centre and attacks it later with ...e5 or ...c5. White's most aggressive plan is the Austrian Attack (f4).",
  ],
  [
    "e4 d6 d4 Nf6 Nc3 g6 f4 Bg7 Nf3",
    "Austrian Attack",
    "B09",
    "Named for Austrian players of the 1930s. The most direct test of the Pirc.",
    "White prepares e5 and a kingside attack; Black counters with ...c5 or ...O-O and ...Na6.",
  ],
  [
    "e4 d6 d4 Nf6 Nc3 g6 Nf3 Bg7 Be2",
    "Pirc, Classical System",
    "B08",
    "The calm treatment: develop and castle.",
    "White keeps the centre and plays h3, Be3; Black plays ...O-O, ...c6 and ...e5 or ...a6.",
  ],
  [
    "e4 d6 d4 Nf6 Nc3 g6 Be3",
    "150 Attack",
    "B07",
    "Named by British club players (rated about 150 ECF) who used it to storm the Pirc with Qd2 and Bh6.",
    "White plays f3, Qd2, Bh6 and h4-h5; Black must counter fast in the centre.",
  ],
  [
    "e4 g6 d4 Bg7",
    "Modern Defence",
    "B06",
    "Karl Robatsch and others made it a system in the 1960s: the Pirc without ...Nf6.",
    "Black delays committing the knight, keeping ...c5, ...d6 or ...c6 and ...d5 options. White has a free hand in the centre.",
  ],
  [
    "e4 Nf6",
    "Alekhine's Defence",
    "B02",
    "Alexander Alekhine introduced it at Budapest 1921, provoking White's pawns forward to attack them later.",
    "Black invites e5, d4, c4 and f4 and then undermines the overextended centre. White must choose between the modest Modern (Nf3) and the ambitious Four Pawns.",
  ],
  [
    "e4 Nf6 e5 Nd5 d4 d6 Nf3",
    "Alekhine, Modern Variation",
    "B04",
    "The solid choice: take space but don't overreach.",
    "White develops and plays Be2, O-O and c4 later; Black chooses ...Bg4 or ...g6.",
  ],
  [
    "e4 Nf6 e5 Nd5 d4 d6 c4 Nb6 f4",
    "Alekhine, Four Pawns Attack",
    "B03",
    "The maximalist approach: take everything.",
    "White's centre is enormous but fragile; Black plays ...dxe5 fxe5 Nc6 and hits d4 hard.",
  ],
  [
    "e4 Nf6 e5 Nd5 d4 d6 c4 Nb6 exd6",
    "Alekhine, Exchange Variation",
    "B03",
    "A quieter reduction of the tension.",
    "Black recaptures with the e-pawn (solid) or c-pawn (active); White has space, Black has no weaknesses.",
  ],
  // ---- King's Gambit, Vienna
  [
    "e4 e5 f4",
    "King's Gambit",
    "C30",
    "Polerio and Greco analysed it; it was the romantic era's favourite, immortalised by Anderssen's 1851 Immortal Game. Fischer's 1961 article \"A Bust to the King's Gambit\" damaged its reputation, but it never died.",
    "White gives a pawn to open the f-file and build a centre with d4. Black can take and hold the pawn, take and return it, or decline with ...Bc5 or the Falkbeer ...d5.",
  ],
  [
    "e4 e5 f4 exf4",
    "King's Gambit Accepted",
    "C33",
    "The principled reply: take the pawn and try to keep it.",
    "White chooses the King's Knight's Gambit (Nf3) or Bishop's Gambit (Bc4). Black's ...g5 holds the pawn at the cost of the kingside.",
  ],
  [
    "e4 e5 f4 exf4 Nf3",
    "King's Knight's Gambit",
    "C34",
    "The classical continuation, stopping ...Qh4+.",
    "Black's main tries are ...g5 (Kieseritzky lines), ...d5 (Modern) and ...Nf6.",
  ],
  [
    "e4 e5 f4 exf4 Nf3 g5 h4 g4 Ne5",
    "Kieseritzky Gambit",
    "C39",
    "Lionel Kieseritzky's line, the setting of the Immortal Game.",
    "White's knight on e5 and the h-file give attacking chances; Black holds the f4 pawn. Wild.",
  ],
  [
    "e4 e5 f4 exf4 Bc4",
    "Bishop's Gambit",
    "C33",
    "Bronstein and Fischer both played it: allow ...Qh4+ and lose castling rights for a tempo.",
    "White plays Kf1 and later Nf3, driving the queen away with gain of time.",
  ],
  [
    "e4 e5 f4 Bc5",
    "King's Gambit Declined",
    "C30",
    "The sensible refusal: the bishop stops White from castling.",
    "Black keeps the centre and aims to punish f4 later with ...d6 and ...Nf6.",
  ],
  [
    "e4 e5 f4 d5",
    "Falkbeer Countergambit",
    "C31",
    "Ernst Falkbeer's 1850s reply: counter a gambit with a gambit.",
    "Black offers a pawn to open the centre before White is ready. After exd5 e4 White's development is awkward.",
  ],
  [
    "e4 e5 Nc3",
    "Vienna Game",
    "C25",
    "Developed by the Viennese masters of the 1850s (Hamppe, Falkbeer) as a delayed King's Gambit.",
    "White prepares f4 with the knight already on c3, or plays Bc4 for Italian-style pressure. Black's ...Nf6 and ...d5 is the freeing plan.",
  ],
  [
    "e4 e5 Nc3 Nf6 f4",
    "Vienna Gambit",
    "C29",
    "The Vienna's teeth: f4 with c3 knight support.",
    "Black should reply ...d5 and after fxe5 Nxe4 has a fine game; ...exf4 is risky because of e5.",
  ],
  [
    "e4 e5 Nc3 Nf6 Bc4",
    "Vienna, 3.Bc4",
    "C28",
    "A positional Vienna leading to Italian-style play.",
    "Black's ...Nxe4 is a temporary sacrifice; ...Nc6 keeps it quiet.",
  ],
  // ---- Queen's Gambit family
  [
    "d4 d5 c4",
    "Queen's Gambit",
    "D06",
    "Recorded in the Göttingen manuscript (c.1490). It became the classical opening of the Steinitz–Lasker–Capablanca era and remains the backbone of 1.d4.",
    "Not a true gambit: White offers the c-pawn to deflect the d5 pawn and claim the centre. Black declines with ...e6 or ...c6, or accepts and returns it for freedom.",
  ],
  [
    "d4 d5 c4 e6",
    "Queen's Gambit Declined",
    "D30",
    "The solid classical answer, played in every world championship of the 1920s and 30s.",
    "Black keeps d5 at the cost of the c8 bishop, which must be freed later with ...c5, ...dxc4 or ...b6. White presses with Nc3, Bg5 and e3.",
  ],
  [
    "d4 d5 c4 e6 Nc3 Nf6 Bg5 Be7 e3 O-O Nf3 Nbd7",
    "QGD, Orthodox Defence",
    "D63",
    "The main line of the 1920s: Capablanca vs Alekhine 1927 was fought largely here.",
    "Black frees with ...c6, ...dxc4 and ...Nd5 (Capablanca's freeing manoeuvre); White keeps a small, lasting edge.",
  ],
  [
    "d4 d5 c4 e6 Nc3 Nf6 Bg5 Be7 e3 O-O Nf3 h6 Bh4 b6",
    "Tartakower Defence",
    "D58",
    "Savielly Tartakower's plan (also credited to Makogonov and Bondarevsky), Karpov's and Kasparov's choice for its reliability.",
    "The bishop comes to b7, solving the classic QGD problem. Balanced and durable.",
  ],
  [
    "d4 d5 c4 e6 Nc3 Nf6 Bg5 Be7 e3 O-O Nf3 h6 Bh4 Ne4",
    "Lasker Defence",
    "D56",
    "Emanuel Lasker's simplifying idea.",
    "Black trades two minor pieces to relieve the cramp, then frees with ...c5. Solid, slightly drawish.",
  ],
  [
    "d4 d5 c4 e6 Nc3 Nf6 Bg5 Nbd7 e3 c6 Nf3 Qa5",
    "Cambridge Springs Defence",
    "D52",
    "Named for the 1904 tournament in Cambridge Springs, Pennsylvania, where it was played repeatedly.",
    "Black pins the c3 knight and eyes the g5 bishop with ...Ne4 and ...Bb4. White must handle the tactics on the a5–e1 diagonal.",
  ],
  [
    "d4 d5 c4 e6 Nc3 Nf6 cxd5 exd5 Bg5",
    "QGD, Exchange Variation",
    "D35",
    "The Carlsbad structure, weaponised by Botvinnik and Kasparov.",
    "White plays the minority attack (b4-b5) to create a weak c6 pawn; Black seeks kingside play with ...Ne4 or ...f5.",
  ],
  [
    "d4 d5 c4 e6 Nc3 c5",
    "Tarrasch Defence",
    "D32",
    "Tarrasch believed free piece play was worth an isolated pawn. Kasparov used it in his 1984 title challenge.",
    "Black accepts an isolated d-pawn for open lines and activity; White plays g3 and Bg2 to pressure d5.",
  ],
  [
    "d4 d5 c4 e6 Nc3 Nf6 Nf3 Bb4",
    "Ragozin Defence",
    "D38",
    "Viacheslav Ragozin's mix of QGD and Nimzo-Indian ideas, a modern favourite.",
    "Black pins and prepares ...dxc4 and ...c5. Flexible and active.",
  ],
  [
    "d4 d5 c4 dxc4",
    "Queen's Gambit Accepted",
    "D20",
    "Steinitz and Alekhine played it; Alekhine's 1937 rematch win over Euwe leaned on it.",
    "Black takes the pawn not to keep it but to free ...c5 and ...e6 quickly. White regains the pawn with Bxc4 and plays for the centre.",
  ],
  [
    "d4 d5 c4 dxc4 Nf3 Nf6 e3 e6 Bxc4 c5 O-O a6",
    "QGA, Classical main line",
    "D27",
    "The standard tabiya of the QGA.",
    "Black plays ...b5 and ...Bb7; White chooses between Qe2 with e4 and a4 to stop the expansion.",
  ],
  [
    "d4 d5 c4 c6",
    "Slav Defence",
    "D10",
    "Analysed by Slavic masters (Alapin, Alekhine, Bogoljubov) in the 1920s. Its virtue: the c8 bishop stays free.",
    "Black supports d5 without blocking the bishop. The main line ...dxc4 with ...Bf5 gives easy development; White fights for e4.",
  ],
  [
    "d4 d5 c4 c6 Nf3 Nf6 Nc3 dxc4 a4 Bf5",
    "Slav, main line",
    "D17",
    "The classical Slav tabiya since Euwe–Alekhine.",
    "White regains the pawn and plays e4 or Ne5; Black keeps the bishop pair active and plays ...e6, ...Bb4.",
  ],
  [
    "d4 d5 c4 c6 cxd5 cxd5",
    "Exchange Slav",
    "D13",
    "The drawing option, though White can press with Bf4 and e3.",
    "Symmetry; the side that misplaces a piece first suffers.",
  ],
  [
    "d4 d5 c4 c6 Nc3 Nf6 Nf3 e6",
    "Semi-Slav Defence",
    "D43",
    "A hybrid of Slav and QGD, sharpened by Botvinnik and later Kramnik and Anand.",
    "Black keeps both ...dxc4 with ...b5 (Meran) and the Botvinnik gambit in reserve. White chooses e3 (Meran) or Bg5 (Botvinnik/Moscow).",
  ],
  [
    "d4 d5 c4 c6 Nc3 Nf6 Nf3 e6 e3 Nbd7 Bd3 dxc4 Bxc4 b5",
    "Meran Variation",
    "D47",
    "From Grünfeld–Rubinstein, Meran 1924.",
    "Black expands with ...b5, ...a6 and ...c5; White plays e4 and a kingside attack. Both sides have their chances.",
  ],
  [
    "d4 d5 c4 c6 Nc3 Nf6 Nf3 e6 Bg5 dxc4 e4 b5",
    "Botvinnik Variation",
    "D44",
    "Botvinnik–Denker, USA–USSR radio match 1945, is the founding game. One of the sharpest lines in all of chess.",
    "White sacrifices a piece for a huge centre and attack; Black keeps material and counterattacks. Memorisation required.",
  ],
  [
    "d4 d5 c4 c6 Nc3 Nf6 Nf3 e6 Bg5 h6 Bxf6",
    "Moscow Variation",
    "D43",
    "A calmer alternative to the Botvinnik.",
    "White gives the bishop pair for a lead in development and e4; Black relies on the bishops long-term.",
  ],
  [
    "d4 d5 c4 Nc6",
    "Chigorin Defence",
    "D07",
    "Chigorin's romantic idea: knights over bishops, activity over structure.",
    "Black gives up the centre and often the bishop pair for piece play. Unfashionable but sound enough.",
  ],
  [
    "d4 d5 c4 e5",
    "Albin Countergambit",
    "D08",
    "Adolf Albin played it against Lasker in 1893. Morozevich revived it a century later.",
    "Black offers a pawn for the advanced d4 wedge and tactics such as the Lasker Trap. White returns to development calmly.",
  ],
  // ---- Indian Defences
  [
    "d4 Nf6",
    "Indian Defence",
    "A45",
    "Named for the Indian player Moheschunder Bannerjee, whose games against Cochrane in the 1850s featured fianchettoes. The hypermoderns of the 1920s built a theory on it.",
    "Black delays ...d5 and keeps flexibility. Which Indian defence follows depends on the second and third moves.",
  ],
  [
    "d4 Nf6 c4 g6 Nc3 Bg7 e4 d6",
    "King's Indian Defence",
    "E70",
    "Hypermodern in spirit (Réti, Nimzowitsch), it was made a fighting weapon by Bronstein and Boleslavsky in the 1940s, then Fischer and Kasparov.",
    "Black concedes the centre, then attacks it with ...e5 or ...c5 and launches a kingside pawn storm. White expands on the queenside. A race.",
  ],
  [
    "d4 Nf6 c4 g6 Nc3 Bg7 e4 d6 Nf3 O-O Be2 e5",
    "KID, Classical Variation",
    "E91",
    "The main line since the 1950s.",
    "After d5 White plays c5 and b4 on the queenside; Black plays ...Ne7, ...f5 and ...g5 for mate. The Mar del Plata race.",
  ],
  [
    "d4 Nf6 c4 g6 Nc3 Bg7 e4 d6 Nf3 O-O Be2 e5 O-O Nc6 d5 Ne7",
    "Mar del Plata Variation",
    "E97",
    "Najdorf–Gligorić, Mar del Plata 1953 set the pattern.",
    "Opposite-wing attacks in their purest form: White's b4-c5, Black's ...f5-f4 and ...g4.",
  ],
  [
    "d4 Nf6 c4 g6 Nc3 Bg7 e4 d6 Nf3 O-O Be2 e5 d5",
    "KID, Petrosian System",
    "E92",
    "Petrosian's idea of closing the centre early to cramp Black.",
    "White plays Bg5 to slow ...f5; Black manoeuvres with ...Na6, ...h6 and ...Nh7.",
  ],
  [
    "d4 Nf6 c4 g6 Nc3 Bg7 e4 d6 f3",
    "Sämisch Variation",
    "E80",
    "Friedrich Sämisch's solid setup, supporting e4 and preparing a queenside castle and g4.",
    "White plays Be3, Qd2 and O-O-O; Black chooses ...c5, ...e5 or the ...Nc6 with ...a6, ...Rb8 plan.",
  ],
  [
    "d4 Nf6 c4 g6 Nc3 Bg7 e4 d6 f4",
    "Four Pawns Attack",
    "E76",
    "The maximalist answer: take all the centre and dare Black to break it.",
    "Black must react at once with ...c5; White's centre is strong but brittle.",
  ],
  [
    "d4 Nf6 c4 g6 g3 Bg7 Bg2 O-O Nf3 d6",
    "KID, Fianchetto Variation",
    "E62",
    "The positional treatment favoured by Korchnoi and Karpov.",
    "White's bishop on g2 blunts Black's kingside attack; Black plays ...Nbd7, ...e5 or the ...c5 Panno setup.",
  ],
  [
    "d4 Nf6 c4 g6 Nc3 Bg7 e4 d6 Be2 O-O Bg5",
    "Averbakh Variation",
    "E73",
    "Yuri Averbakh's bishop pin, preventing an early ...e5.",
    "White's Qd2 and O-O-O ideas; Black plays ...c5 or ...Na6 and ...e5 later.",
  ],
  [
    "d4 Nf6 c4 e6 Nc3 Bb4",
    "Nimzo-Indian Defence",
    "E20",
    'Aron Nimzowitsch\'s creation of the 1920s, explained in "My System": control the centre with pieces, not pawns.',
    "Black pins the knight and threatens to double White's pawns, fighting for e4. White's choices (e3, Qc2, a3, f3) each define a different middlegame.",
  ],
  [
    "d4 Nf6 c4 e6 Nc3 Bb4 e3",
    "Rubinstein Variation",
    "E40",
    "Rubinstein's flexible development, the most popular reply since the 1930s.",
    "White develops with Bd3, Nf3 and O-O; Black chooses ...O-O with ...d5 and ...c5, or the ...b6 fianchetto.",
  ],
  [
    "d4 Nf6 c4 e6 Nc3 Bb4 e3 O-O Bd3 d5 Nf3 c5",
    "Rubinstein, main line",
    "E53",
    "The classical tabiya with a full centre battle.",
    "After O-O Nc6 Black eyes ...dxc4 and ...Bxc3; White accepts doubled pawns for the bishop pair and a central mass.",
  ],
  [
    "d4 Nf6 c4 e6 Nc3 Bb4 Qc2",
    "Classical (Capablanca) Variation",
    "E32",
    "Capablanca's answer: recapture on c3 with the queen and keep the structure.",
    "White avoids doubled pawns at the cost of a tempo; Black plays ...O-O, ...c5 or ...d5 quickly.",
  ],
  [
    "d4 Nf6 c4 e6 Nc3 Bb4 a3 Bxc3+ bxc3",
    "Sämisch Variation",
    "E25",
    "Sämisch's forcing line: accept the doubled pawns for the bishop pair and a big centre.",
    "White plays f3 and e4; Black blockades with ...c5, ...Nc6 and ...Ba6 to attack the c4 weakness.",
  ],
  [
    "d4 Nf6 c4 e6 Nc3 Bb4 Bg5",
    "Leningrad Variation",
    "E30",
    "Spassky's pin, developed by Leningrad players.",
    "White keeps the pin; Black replies ...h6, ...c5 and ...d6 with ...e5.",
  ],
  [
    "d4 Nf6 c4 e6 Nc3 Bb4 Nf3",
    "Kasparov Variation",
    "E21",
    "Kasparov used it early in his career to reach fresh positions.",
    "White delays commitment; Black chooses ...c5, ...b6 or ...O-O.",
  ],
  [
    "d4 Nf6 c4 e6 Nf3 b6",
    "Queen's Indian Defence",
    "E12",
    "Nimzowitsch's sister opening to the Nimzo-Indian: control e4 from b7.",
    "Black fianchettoes and holds e4 with pieces. White's g3 (Rubinstein) or a3 (Petrosian, stopping ...Bb4) are the main tries.",
  ],
  [
    "d4 Nf6 c4 e6 Nf3 b6 g3 Bb7 Bg2 Be7 O-O O-O",
    "Queen's Indian, Classical",
    "E17",
    "The old main line, a Karpov speciality.",
    "Quiet, symmetrical fianchettoes; White plays Nc3 and Qc2 with e4, Black ...d5 or ...Ne4.",
  ],
  [
    "d4 Nf6 c4 e6 Nf3 b6 a3",
    "Petrosian Variation",
    "E12",
    "Petrosian's prophylaxis against ...Bb4; Kasparov's main weapon in the 1980s.",
    "White prepares Nc3 and d5 or e4; Black plays ...Bb7 and ...d5.",
  ],
  [
    "d4 Nf6 c4 e6 Nf3 b6 g3 Ba6",
    "Queen's Indian, 4...Ba6",
    "E15",
    "Nimzowitsch's provocative bishop, hitting c4.",
    "White must defend c4 awkwardly with b3 or Qc2; Black gains time for ...Bb4+ and ...c5.",
  ],
  [
    "d4 Nf6 c4 e6 Nf3 Bb4+",
    "Bogo-Indian Defence",
    "E11",
    "Efim Bogoljubov's check, a sound alternative to the Queen's Indian.",
    "After Bd2 Black chooses ...Qe7, ...a5 or ...Bxd2+. Solid and low-theory.",
  ],
  [
    "d4 Nf6 c4 g6 Nc3 d5",
    "Grünfeld Defence",
    "D80",
    "Ernst Grünfeld introduced it against Alekhine in Vienna 1922. Fischer used it to beat Botvinnik; Kasparov made it his main defence.",
    "Black lets White build a full pawn centre and attacks it from a distance with ...Bg7, ...c5 and ...Nc6. The centre is the target, not the prize.",
  ],
  [
    "d4 Nf6 c4 g6 Nc3 d5 cxd5 Nxd5 e4 Nxc3 bxc3 Bg7",
    "Exchange Variation",
    "D85",
    "The principled main line: build the centre and defend it.",
    "White chooses Nf3 with Rb1 (modern) or Bc4 with Ne2 (classical). Black hits d4 with ...c5, ...Nc6 and ...Qa5.",
  ],
  [
    "d4 Nf6 c4 g6 Nc3 d5 cxd5 Nxd5 e4 Nxc3 bxc3 Bg7 Bc4",
    "Exchange, Classical 7.Bc4",
    "D87",
    "The classical setup with Ne2 to keep the f3 square for the f-pawn.",
    "White plays Be3, O-O and pushes d5; Black plays ...c5, ...Nc6 and ...Bg4.",
  ],
  [
    "d4 Nf6 c4 g6 Nc3 d5 Nf3 Bg7 Qb3",
    "Russian Variation",
    "D96",
    "Botvinnik and Smyslov's early queen sortie, forcing ...dxc4.",
    "White regains the pawn with tempo and gets e4; Black counters with ...Bg4 or ...a6 and ...b5.",
  ],
  [
    "d4 Nf6 c4 g6 Nc3 d5 Bf4",
    "Grünfeld, 4.Bf4",
    "D82",
    "A solid development scheme popular in the 1930s.",
    "White holds the centre with e3; Black plays ...Bg7 and ...c5 to free the game.",
  ],
  [
    "d4 Nf6 c4 c5 d5 e6 Nc3 exd5 cxd5 d6",
    "Modern Benoni",
    "A60",
    'The Benoni ("son of sorrow" in Hebrew) appears in Aaron Reinganum\'s 1825 book. Tal turned the Modern Benoni into a fighting weapon in the 1950s.',
    "Black accepts a cramped d6 pawn for a queenside majority and dynamic piece play (...Bg7, ...Re8, ...b5). White has central space and the e5 break.",
  ],
  [
    "d4 Nf6 c4 c5 d5 b5",
    "Benko Gambit",
    "A57",
    "Pal Benko popularised it in the 1960s (also the Volga Gambit).",
    "Black gives a pawn for lasting pressure on the a- and b-files with ...Bg7 and ...Qa5. Compensation is positional, not tactical.",
  ],
  [
    "d4 f5",
    "Dutch Defence",
    "A80",
    "Elias Stein recommended it in 1789. Botvinnik and later Nakamura used it as a fighting weapon.",
    "Black stakes out e4 and aims at the kingside. The weakened e8–h5 diagonal is the price. Leningrad, Stonewall and Classical are the three main systems.",
  ],
  [
    "d4 f5 c4 Nf6 g3 g6",
    "Leningrad Dutch",
    "A87",
    "Developed in Leningrad in the 1950s: a Dutch with a King's Indian bishop.",
    "Black plays ...Bg7, ...O-O, ...d6 and ...e5 or ...c6 with ...Qe8. Sharp.",
  ],
  [
    "d4 f5 c4 Nf6 g3 e6 Bg2 d5",
    "Stonewall Dutch",
    "A90",
    "A pawn wall (d5, e6, f5) that Botvinnik used to win world championship games.",
    "Black secures e4 for a knight and attacks on the kingside; the hole on e5 and the bad c8 bishop are the drawbacks.",
  ],
  // ---- Queen's pawn systems
  [
    "d4 d5 Bf4",
    "London System",
    "D02",
    "Named for the London 1922 tournament, where Réti, Capablanca and Alekhine all used it. A 2010s explosion in popularity (Carlsen, Kamsky) made it the club player's favourite.",
    "White develops the bishop outside the pawn chain, then plays e3, c3, Nbd2 and Bd3: the same setup against almost everything. Solid, low-theory, with kingside chances.",
  ],
  [
    "d4 Nf6 Bf4",
    "London System vs ...Nf6",
    "A45",
    "The flexible London move order.",
    "White's setup is identical; Black's ...c5 and ...Qb6 pressure on b2 is the main challenge.",
  ],
  [
    "d4 d5 Bf4 Nf6 e3 c5 c3 Nc6 Nd2 e6 Ngf3",
    "London System, main line",
    "D02",
    "The standard London tabiya.",
    "White plays Bd3, O-O and often Ne5 with a kingside attack; Black plays ...Bd6 and ...Qb6 or ...O-O.",
  ],
  [
    "d4 d5 Nf3 Nf6 e3",
    "Colle System",
    "D04",
    "Edgard Colle's 1920s system: a quiet buildup ending with an e4 break.",
    "White plays Bd3, c3, Nbd2 and e4; the Colle–Zukertort version uses b3 and Bb2 instead of c3.",
  ],
  [
    "d4 Nf6 Nf3 e6 Bg5",
    "Torre Attack",
    "A46",
    "Carlos Torre beat Lasker with it in Moscow 1925 (the famous windmill game).",
    "White pins and plays e3, Nbd2 and c3; Black frees with ...c5 and ...h6.",
  ],
  [
    "d4 Nf6 Bg5",
    "Trompowsky Attack",
    "A45",
    "Octávio Trompowsky, Brazilian champion of the 1930s and 40s. Hodgson and Adams revived it in the 1990s.",
    "White threatens to double Black's pawns and avoids Indian defences entirely. Black replies ...Ne4, ...e6 or ...c5.",
  ],
  // ---- Flank openings
  [
    "c4",
    "English Opening",
    "A10",
    "Howard Staunton, the Englishman, used it against Saint-Amant in 1843. Botvinnik, Karpov and Kasparov gave it world championship credentials.",
    "A flank claim on d5 without committing the centre. White often fianchettoes with g3; Black chooses ...e5 (Reversed Sicilian), ...c5 (Symmetrical) or ...Nf6 with ...e6.",
  ],
  [
    "c4 e5",
    "Reversed Sicilian",
    "A20",
    "The natural reply: give White a Sicilian with an extra tempo and see if it matters.",
    "Black stakes out d4; White plays Nc3, g3 and Bg2 or the Botvinnik system with e4.",
  ],
  [
    "c4 e5 Nc3 Nf6 Nf3 Nc6",
    "English, Four Knights",
    "A28",
    "A standard Reversed Sicilian setup.",
    "White chooses g3, e3 or d4; Black plays ...Bb4 or ...d5.",
  ],
  [
    "c4 e5 Nc3 Nf6 g3 d5 cxd5 Nxd5 Bg2",
    "English, Reversed Dragon",
    "A22",
    "A Dragon Sicilian with colours reversed and a tempo up.",
    "White's Bg2 eyes the queenside; Black's knight on d5 and ...Nb6 plan hold the centre.",
  ],
  [
    "c4 c5",
    "Symmetrical English",
    "A30",
    "The equaliser's choice, played by Petrosian and Karpov.",
    "Mirrored structures; the Hedgehog (Black's ...b6, ...d6, ...a6) and the Botvinnik setup are the main plans.",
  ],
  [
    "c4 c5 Nc3 Nc6 g3 g6 Bg2 Bg7 e4",
    "Botvinnik System",
    "A36",
    "Botvinnik's pawn triangle (c4, d3, e4) with a fianchetto.",
    "White clamps d5 and plays f4 for a kingside attack; Black mirrors or plays ...e6 and ...d5.",
  ],
  [
    "c4 Nf6 Nc3 e6 e4",
    "Mikėnas–Carls Variation",
    "A18",
    "Vladas Mikėnas's aggressive push against the Nimzo-style setup.",
    "White threatens e5; Black replies ...d5 or ...c5 with sharp play.",
  ],
  [
    "Nf3 d5 c4",
    "Réti Opening",
    "A09",
    "Richard Réti's hypermodern system beat Capablanca at New York 1924, ending his eight-year unbeaten run.",
    "White attacks d5 from the flank and fianchettoes one or both bishops. Black holds with ...e6 or ...c6, or advances ...d4.",
  ],
  [
    "Nf3 d5 c4 dxc4",
    "Réti Accepted",
    "A09",
    "Black takes the pawn; White regains it with Na3 or Qa4+.",
    "White gets a lead in development; Black must return the pawn sensibly.",
  ],
  [
    "Nf3 d5 c4 d4",
    "Réti, Advance Variation",
    "A09",
    "Black grabs space, creating a reversed Benoni.",
    "White undermines with e3 and b4; Black defends d4 with ...c5 and ...Nc6.",
  ],
  [
    "Nf3 d5 g3",
    "King's Indian Attack",
    "A07",
    "Fischer's favourite universal system against 1...e6 and 1...c6 players.",
    "White plays Bg2, O-O, d3, Nbd2, e4 and a kingside attack with e5 and h4. Same plan every game.",
  ],
  [
    "d4 Nf6 c4 e6 g3 d5 Bg2",
    "Catalan Opening",
    "E01",
    "Named when Tartakower was asked to honour Catalonia at Barcelona 1929. Kramnik and Carlsen made it a modern main line.",
    "White combines the Queen's Gambit with a fianchetto: the g2 bishop presses the long diagonal. Black either takes on c4 (Open Catalan) or holds with ...Be7 (Closed).",
  ],
  [
    "d4 Nf6 c4 e6 g3 d5 Bg2 dxc4",
    "Open Catalan",
    "E02",
    "Black takes the pawn and tries to keep it with ...a6 and ...b5.",
    "White regains it with Qa4+ or Qc2 and keeps long-term pressure.",
  ],
  [
    "d4 Nf6 c4 e6 g3 d5 Bg2 Be7 Nf3 O-O O-O",
    "Closed Catalan",
    "E06",
    "The solid main line of the Catalan.",
    "Black plays ...dxc4 later or ...c6 and ...b6; White presses with Qc2, Nbd2 and e4.",
  ],
  [
    "f4",
    "Bird's Opening",
    "A02",
    "Henry Bird's 19th-century speciality, a reversed Dutch.",
    "White stakes out e5 and often fianchettoes with b3 and Bb2. Black's ...d5 is the standard reply; ...e5 (From's Gambit) the sharp one.",
  ],
  [
    "b3",
    "Nimzo-Larsen Attack",
    "A01",
    "Nimzowitsch played it in the 1920s; Bent Larsen made it his own in the 1960s and 70s.",
    "White fianchettoes at once, targeting e5 and the long diagonal. Flexible and provocative.",
  ],
];
