import type { Story } from "./stories";

function family(
  moves: string,
  name: string,
  slug: string,
  history: string,
  idea: string,
  counter: string,
): { moves: string; story: Story } {
  const historySource: Record<string, { title: string; url: string }> = {
    "Modern-Defense": {
      title: "Bryan Smith: The Modern Defense, a history",
      url: "https://www.chess.com/article/view/the-modern-defense-a-history",
    },
    "Torre-Attack": {
      title: "Torre Attack: Carlos Torre and historical examples",
      url: "https://en.wikipedia.org/wiki/Torre_Attack",
    },
  };
  return {
    moves,
    story: {
      scope: `${name}: the wider story`,
      history,
      idea,
      counter,
      sources: [
        {
          title: `Chess.com: ${name}, plans and history`,
          url: `https://www.chess.com/openings/${slug}`,
        },
        ...(historySource[slug] ? [historySource[slug]] : []),
      ],
    },
  };
}

// Match move prefixes, not ECO ranges: nearby ECO codes can represent unrelated systems.
// Variation-specific original prose is retained above these explicitly labelled family stories.
export const OPENING_STORIES = [
  family(
    "e4 e5",
    "Open games",
    "Italian-Game",
    "The Italian tradition is one of the oldest branches of open-game chess. Early analysts explored rapid development and attacks on the king; later practice also developed quiet build-ups. The linked Italian guide is a historical example within this wider family, not a claim that every 1.e4 e5 game is an Italian.",
    "Both sides occupy the centre. Developing with threats and preparing a central pawn exchange can open useful lines before the opponent is ready.",
    "Develop, defend the central pawns and prepare a safe challenge to the centre. Avoid chasing material while the king and queenside pieces remain at home.",
  ),
  family(
    "e4 e5 Nf3 Nc6 Bb5",
    "Ruy Lopez",
    "Ruy-Lopez-Opening",
    "Ruy López’s 1561 analysis gave this opening its enduring name. It became a central battleground of elite chess in the nineteenth century. Kramnik’s use of the Berlin against Kasparov in 2000 is a later example of a venerable branch gaining new fame through a championship match.",
    "White develops while pressuring the knight that supports e5. The lasting aim is central control, not an automatic win of that pawn.",
    "Black needs coordinated development and a timely central challenge. Decide whether to preserve the pawn tension, exchange into an ending, or seek active piece play according to the chosen variation.",
  ),
  family(
    "e4 e5 Nf3 Nc6 Bc4",
    "Italian Game",
    "Italian-Game",
    "The Italian Game grew out of early Italian opening analysis, with Greco among its influential teachers. Its long life comes from flexibility: the same bishop placement can lead to gambits or patient manoeuvring. Modern use of quieter lines demonstrates that an old opening can support a different style.",
    "The bishop watches f7 while White develops toward castling. A prepared d4 advance can turn that pressure into an open centre.",
    "Black should develop and prepare ...d5 when it works. Check tactics near f7, but do not defend so passively that White builds an uncontested centre.",
  ),
  family(
    "e4 e5 Nf3 Nc6 d4",
    "Scotch Game",
    "Scotch-Game",
    "The Scotch takes its name from the nineteenth-century Edinburgh–London correspondence contest. Kasparov later helped revive it in top-level practice. Its appeal is direct: White resolves the central tension early and asks both sides to find active squares.",
    "Exchanging central pawns opens lines and gives White room. The early clarification also gives Black concrete targets and developing moves.",
    "Develop with pressure on the centre rather than trying to hold an extra pawn at any cost. White should avoid repeated moves with the queen while undeveloped pieces wait.",
  ),
  family(
    "e4 e5 Nf3 Nf6",
    "Petrov’s Defense",
    "Petrovs-Defense",
    "Named after Alexander Petrov, this counterattacking defence gained an enduring reputation for solidity. Its symmetry can be misleading: the order of captures and checks matters, and careless imitation can lose material.",
    "Black attacks e4 instead of simply defending e5, reducing White’s chance to build pressure for free.",
    "White can seek active development and central space. Black must calculate before copying a capture; symmetry is not a substitute for checking threats.",
  ),
  family(
    "e4 e5 Nf3 d6",
    "Philidor Defense",
    "Philidor-Defense",
    "Philidor’s name connects this defence with the eighteenth-century emphasis on pawn structure. Its compact centre offers security at the cost of space. The opening’s history is a reminder that a sound pawn chain still needs a plan to release the pieces behind it.",
    "The d6-pawn supports e5 without committing the queen’s knight. Black aims to complete development before challenging the centre.",
    "White should use the extra space without overextending. Black should prepare an active break or exchange instead of accepting permanent congestion.",
  ),
  family(
    "e4 c5",
    "Sicilian Defense",
    "Sicilian-Defense",
    "The Sicilian has early roots in chess literature, but its fighting reputation grew through generations of master practice. Fischer and Kasparov made its sharp branches especially familiar. Its many named variations represent different answers to the same question: how can Black fight for the initiative against 1.e4?",
    "Black attacks d4 from the flank. In many open variations the c-pawn trades for White’s central d-pawn, leaving an imbalanced position with chances on different parts of the board.",
    "White uses development and central space; Black needs counterplay before being attacked. Judge pawn storms by the king positions and open lines, not by the opening’s aggressive reputation.",
  ),
  family(
    "e4 e6",
    "French Defense",
    "French-Defense",
    "The name recalls the Paris–London correspondence match of 1834. The defence became a durable way to challenge a large centre with a compact pawn chain. Different French variations tell different stories, but the struggle between space and counterattack connects them.",
    "Black prepares ...d5. Closed centres can give White room for kingside play while Black challenges the supporting pawns.",
    "White should reinforce the centre without losing development time. Black must find activity for the light-squared bishop and choose a well-prepared pawn break.",
  ),
  family(
    "e4 c6",
    "Caro-Kann Defense",
    "Caro-Kann-Defense",
    "Horatio Caro and Marcus Kann gave this defence its name through nineteenth-century analysis and practice. Later champions including Capablanca and Karpov helped establish its solid reputation. Its appeal is structural reliability with a route for the light-squared bishop to develop.",
    "Black prepares ...d5 while retaining the option to develop the c8-bishop before ...e6 closes its diagonal.",
    "White can gain space or accelerate development. Black should not mistake solidity for waiting: complete development and challenge the centre when the pieces are ready.",
  ),
  family(
    "e4 d5",
    "Scandinavian Defense",
    "Scandinavian-Defense",
    "The Scandinavian is among the oldest recorded defences to 1.e4. Its straightforward central challenge survived despite the apparent loss of time when White attacks the early queen. That trade-off gives the opening a distinctive practical character.",
    "Black resolves the central pawn tension immediately, often aiming for a clear, compact structure afterward.",
    "White should develop with useful attacks on the queen. Black needs safe queen squares and efficient development; moving the queen repeatedly without a reason gives away the opening’s simplicity.",
  ),
  family(
    "e4 d6",
    "Pirc Defense",
    "Pirc-Defense",
    "Vasja Pirc helped popularize this approach as hypermodern ideas gained acceptance. Black allows a broad centre and challenges it later, rather than trying to match White’s pawn occupation immediately.",
    "Flexible development and a fianchetto bishop can pressure the centre from a distance. Black trades space for the chance to strike at committed pawns.",
    "White should support the centre and develop before attacking. Black must choose a timely central break; delaying every confrontation can simply leave a cramped position.",
  ),
  family(
    "e4 g6",
    "Modern Defense",
    "Modern-Defense",
    "Also associated with Karl Robatsch, the Modern belongs to the family of defences that delay direct occupation of the centre. Its development involved several players, so the alternative names should not be read as proof of a single inventor.",
    "The bishop on g7 puts distant pressure on central squares while Black keeps the knight’s destination flexible.",
    "White can build a supported centre and use the extra space. Black needs an eventual pawn challenge and must watch king safety while delaying conventional development.",
  ),
  family(
    "e4 Nf6",
    "Alekhine’s Defense",
    "Alekhines-Defense",
    "Alekhine brought this provocative defence to prominence at Budapest in 1921. Its later specialists showed that retreating a knight can be part of a plan, provided the advancing pawns become targets rather than a permanent space advantage.",
    "Black tempts White’s pawns forward, then attacks the expanded centre with pieces and pawn breaks.",
    "White should develop behind the pawn centre instead of chasing the knight indefinitely. Black must attack the centre before the lost tempi turn into a decisive lag in development.",
  ),
  family(
    "e4 e5 f4",
    "King’s Gambit",
    "Kings-Gambit",
    "A favourite of the Romantic attacking tradition, the King’s Gambit offered the f-pawn for activity and open lines. Its historical fame owes much to spectacular attacking games; that fame should not hide the risks to White’s own king.",
    "White challenges e5 and may open the f-file. The initiative has to justify the pawn and weakened king position.",
    "Black should develop quickly and return material when useful. White needs forcing play and a safe king rather than assuming a pawn offer creates an attack by itself.",
  ),
  family(
    "e4 e5 Nc3",
    "Vienna Game",
    "Vienna-Game",
    "The Vienna grew as a way to prepare ideas resembling a delayed King’s Gambit. Its history also includes quieter development, making it a choice between a pawn challenge and a more restrained centre.",
    "Nc3 supports e4 while keeping the f-pawn free to advance. White postpones choosing the king’s knight’s square.",
    "Black should contest the centre and assess whether ...d5 is possible. White must still account for the king’s diagonal before advancing the f-pawn.",
  ),
  family(
    "d4 d5",
    "Queen’s-pawn play",
    "Queens-Gambit",
    "Queen’s-pawn openings became central to positional master chess around the turn of the twentieth century. The Queen’s Gambit is a major historical example, though a game beginning 1.d4 d5 can choose a different system before c4 is played.",
    "The d-pawns establish central footholds. Both sides need development and a plan for challenging the opposing centre.",
    "Use pawn breaks to prevent a passive squeeze. A familiar setup still needs to respond to the opponent’s actual threats.",
  ),
  family(
    "d4 d5 c4",
    "Queen’s Gambit",
    "Queens-Gambit",
    "Recorded in the Göttingen manuscript around 1490, the Queen’s Gambit gained great prominence with positional chess. Capablanca and Alekhine used it in 32 of their 34 championship games in 1927, an extraordinary illustration of how one opening family can sustain many different battles.",
    "White uses a flank pawn to challenge Black’s central d-pawn. Black may accept the exchange or preserve the centre with support.",
    "Black should prioritize development and a central counter-break over clinging to a captured c-pawn. White should convert central pressure into active pieces rather than chase an automatic attack.",
  ),
  family(
    "d4 Nf6",
    "Indian defenses",
    "Kings-Indian-Defense",
    "The Indian defences belong to the wider history of challenging central pawns with pieces and delayed pawn breaks. They are a family, not a single inventor’s system. The linked King’s Indian is one influential example; the game may choose another branch.",
    "The knight contests e4 without committing Black’s central pawns. Later moves decide whether the struggle becomes a blockade, a central exchange or an attack on the wings.",
    "White should develop behind the centre; Black must eventually challenge it. A large centre and pressure from a distance are competing resources, not automatic advantages.",
  ),
  family(
    "d4 Nf6 c4 g6",
    "King’s Indian Defense",
    "Kings-Indian-Defense",
    "Fischer and Kasparov were prominent champions of the King’s Indian. Their games helped make its counterattacking reputation familiar: Black accepts less space and fights against White’s centre rather than trying to mirror it.",
    "The fianchettoed bishop and central pawn breaks create activity. In closed centres, the direction of pawn chains can guide attacks on opposite wings.",
    "White needs a plan that uses space while respecting the kingside attack. Black cannot attack by habit; the centre must be stable enough to justify wing play.",
  ),
  family(
    "d4 Nf6 c4 e6 Nc3 Bb4",
    "Nimzo-Indian Defense",
    "Nimzo-Indian-Defense",
    "Nimzowitsch helped turn restraint of the centre into an opening philosophy. This defence illustrates it directly: the bishop limits the c3-knight’s support of e4. Generations of master practice explored whether doubled pawns or the bishop pair matter more afterward.",
    "Black controls e4 with pieces and may exchange bishop for knight to alter White’s pawn structure.",
    "White should choose how to meet the pin and whether to accept structural changes. Black must use development and targets to justify giving up a bishop.",
  ),
  family(
    "d4 Nf6 c4 e6 Nf3 b6",
    "Queen’s Indian Defense",
    "Queens-Indian-Defense",
    "The Queen’s Indian is part of the hypermodern opening tradition and became a major strategic battleground. Its quiet appearance conceals a contest for e4 and the long diagonal, with piece placement often mattering more than an immediate attack.",
    "Black develops the queen’s bishop toward the centre while retaining a flexible pawn structure.",
    "White can challenge the diagonal and prepare central expansion. Black needs to contest the centre actively rather than rely on the bishop’s distant aim alone.",
  ),
  family(
    "d4 Nf6 c4 e6 Nf3 Bb4+",
    "Bogo-Indian Defense",
    "Bogo-Indian-Defense",
    "Named for Efim Bogoljubov, the Bogo-Indian uses a checking bishop move to influence how White completes development. Its appeal is practical economy: Black can seek useful exchanges before deciding the final central structure.",
    "The check asks White to commit a blocking piece. Exchanges can ease Black’s development and reduce crowding.",
    "White should select the interposition with a clear development plan. Black must avoid trading so many active pieces that the remaining position is merely passive.",
  ),
  family(
    "d4 Nf6 c4 g6 Nc3 d5",
    "Grünfeld Defense",
    "Grunfeld-Defense",
    "Ernst Grünfeld gave his name to this defence, later a major weapon for Kasparov. Its historical message is striking: Black can permit a large pawn centre and then make that centre the focus of sustained pressure.",
    "Exchanges can leave White with central pawns while Black’s bishop and pieces attack their support.",
    "White should coordinate development before pushing the centre further. Black must create concrete pressure quickly, before the pawns gain space without cost.",
  ),
  family(
    "d4 Nf6 c4 c5",
    "Benoni Defense",
    "Benoni-Defense",
    "The Benoni name traces to Aaron Reinganum’s nineteenth-century writing. Its modern branches became associated with unbalanced, fighting chess: White’s space is set against Black’s active pieces and queenside chances.",
    "Black challenges d4 from the side. When White advances d5, the resulting asymmetry offers both targets and opportunities.",
    "White should restrict counterplay while developing. Black needs active breaks and piece coordination; accepting a cramped position without a release plan wastes the imbalance.",
  ),
  family(
    "d4 Nf6 c4 c5 d5 b5",
    "Benko Gambit",
    "Benko-Gambit",
    "Pal Benko popularized this gambit although earlier examples predate his use. It became famous for a different kind of compensation: enduring queenside pressure instead of an immediate mating attack.",
    "Black offers a pawn to open files and activate the bishop toward the queenside. Rook pressure can remain useful even after queens are exchanged.",
    "White should consolidate and contest the open files. Returning the pawn to blunt the pressure can be wiser than defending it with every piece.",
  ),
  family(
    "d4 f5",
    "Dutch Defense",
    "Dutch-Defense",
    "The Dutch has no single clear philosophical origin in the linked history. Botvinnik became a prominent world-champion practitioner; Tartakower’s 1922 win against Maroczy is a classic Stonewall example. These games helped establish the appeal of claiming e4 and then seeking kingside play.",
    "Black gains influence over e4 and possible kingside space, but weakens squares near the king immediately.",
    "White can challenge the centre and exploit the weakened king diagonals. Black should finish development and judge central safety before launching a pawn attack.",
  ),
  family(
    "d4 d5 Bf4",
    "London System",
    "London-System",
    "The 1922 London Congress helped give this setup its name and prominence. Later use by Kamsky and Carlsen brought renewed attention. The attraction is a repeatable development plan, though strong play still adapts it to Black’s choices.",
    "The bishop develops outside the pawn chain before e3. A supported centre leaves the pieces free to prepare a central break or kingside play.",
    "Black can challenge d4 with ...c5 and put pressure on the queenside. White should watch b2 and the exposed bishop instead of making setup moves automatically.",
  ),
  family(
    "d4 Nf6 Bf4",
    "London System",
    "London-System",
    "This move order reaches the London tradition through ...Nf6. The 1922 London Congress and later advocates such as Kamsky and Carlsen helped popularize the setup; there is no need to credit one inventor for every natural bishop development.",
    "White develops the bishop before closing its diagonal with e3 and aims for a stable centre.",
    "Black can test the setup with ...c5 and queenside pressure. White should adapt to that challenge rather than insist on the same pawn formation in every game.",
  ),
  family(
    "d4 d5 Nf3 Nf6 e3",
    "Colle System",
    "Colle-System",
    "Edgard Colle popularized this compact development system in the 1920s. Related setups associated with Koltanowski and Zukertort show how one formation can lead either to a central pawn break or a bishop aimed from b2.",
    "White develops safely and prepares e4 or kingside activity. The quiet early moves are preparation, not the whole plan.",
    "Black should contest e4 and develop actively. White must find a role for the c1-bishop rather than leave it behind the pawn chain indefinitely.",
  ),
  family(
    "d4 Nf6 Nf3 e6 Bg5",
    "Torre Attack",
    "Torre-Attack",
    "The Torre is associated with Carlos Torre and the practical use of a bishop pin in a queen’s-pawn setup. It connects opening development with the pin theme that can persist into the middlegame.",
    "White develops with pressure on the f6-knight, then supports the centre without committing to c4 immediately.",
    "Black can challenge the centre with ...c5 and resolve the pin when useful. White should avoid treating a pin as permanent if Black can break it easily.",
  ),
  family(
    "d4 Nf6 Bg5",
    "Trompowsky Attack",
    "Trompowsky-Attack",
    "Brazilian master Octávio Trompowsky gave this opening its name. Later advocates, notably Julian Hodgson, helped make the early bishop move a practical way to leave the heavily studied Indian main lines.",
    "White immediately questions the knight and may exchange it to change Black’s pawns. The bishop’s early activity also makes it a possible target.",
    "Black can challenge the bishop or centre rather than defend passively. White needs a development plan after the initial exchange or retreat.",
  ),
  family(
    "c4",
    "English Opening",
    "English-Opening",
    "Howard Staunton helped establish the English in nineteenth-century practice. Its flexibility later appealed to many positional players: White can pressure the centre from the flank and choose the pawn structure after seeing Black’s setup.",
    "The c-pawn contests d5 without committing the d- and e-pawns. A fianchetto can reinforce pressure across the long diagonal.",
    "Black should establish central influence with development and suitable pawn breaks. White should turn flexibility into a concrete plan before falling behind in development.",
  ),
  family(
    "Nf3",
    "Réti Opening",
    "Reti-Opening",
    "Richard Réti’s name is closely linked to hypermodern chess, including his celebrated 1924 win over Capablanca. The wider lesson is that pieces and flank pawns can challenge a centre before White occupies it directly.",
    "White develops a knight and keeps several central pawn setups available. Later pawn pressure can challenge whichever centre Black builds.",
    "Black should occupy useful central squares with support, avoiding an overextended pawn front. White must eventually challenge that centre rather than merely watch it.",
  ),
  family(
    "Nf3 d5 g3",
    "King’s Indian Attack",
    "Kings-Indian-Attack",
    "The King’s Indian Attack became especially associated with Fischer’s attacking games. It uses a familiar fianchetto setup with White, but its extra move and the opponent’s pawn structure make it a distinct practical problem.",
    "A sheltered king and coordinated pieces prepare a central or kingside advance. The setup is a platform for a plan, not an automatic attack.",
    "Black should challenge the centre and seek space on the other wing when appropriate. White should not start a pawn storm before the centre and pieces support it.",
  ),
  family(
    "d4 Nf6 c4 e6 g3",
    "Catalan Opening",
    "Catalan-Opening",
    "The Catalan name dates to the 1929 Barcelona tournament and its connection with Tartakower. It combines queen’s-pawn central play with a fianchetto, creating an opening famous for pressure that can outlast the opening phase.",
    "The g2-bishop supports central and queenside pressure. White may offer a pawn for development and long-diagonal activity.",
    "Black should either hold the pawn with a concrete development plan or return it to free the pieces. White must justify any pawn investment with active pressure.",
  ),
  family(
    "f4",
    "Bird’s Opening",
    "Birds-Opening",
    "Henry Bird’s nineteenth-century practice gave 1.f4 its familiar name, although the move predates him. Its resemblance to the Dutch with colours reversed helps explain its plans, but White’s first-move choice comes with immediate king-safety responsibilities.",
    "White claims e5 and may build kingside pressure. The f-pawn’s departure also opens a diagonal toward the king.",
    "Black can develop toward the centre or challenge it immediately. White should calculate checks and gambit responses before assuming the extra space is an advantage.",
  ),
  family(
    "b3",
    "Nimzowitsch-Larsen Attack",
    "Nimzowitsch-Larsen-Attack",
    "The linked history records 1.b3 in a serious game by van’t Kruijs in 1851. Nimzowitsch became associated with it later; Larsen’s repeated use from 1968 made it a recognizable weapon. Fischer also won with it in 1970. Larsen’s famous loss to Spassky shows why its flexibility still needs rapid development.",
    "Bb2 aims at the long diagonal while White keeps central pawns flexible. The bishop becomes powerful when the centre opens, but a blocked diagonal can leave it watching its own pawns.",
    "Black can occupy the centre with ...e5 or ...d5 and develop naturally. Avoid overextending the centre into an easy target; White should complete development before launching a flank adventure.",
  ),
];
